//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Teams.Apps.GoalTracker {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Teams.Apps.GoalTracker.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add note.
        /// </summary>
        public static string AddNoteButtonText {
            get {
                return ResourceManager.GetString("AddNoteButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date:.
        /// </summary>
        public static string AddNoteDateSubheading {
            get {
                return ResourceManager.GetString("AddNoteDateSubheading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string AddNoteEditButtonText {
            get {
                return ResourceManager.GetString("AddNoteEditButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field cannot be empty.
        /// </summary>
        public static string AddNoteEmptyGoalError {
            get {
                return ResourceManager.GetString("AddNoteEmptyGoalError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field cannot be empty.
        /// </summary>
        public static string AddNoteEmptyNoteError {
            get {
                return ResourceManager.GetString("AddNoteEmptyNoteError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goal:.
        /// </summary>
        public static string AddNoteGoalNameSubheading {
            get {
                return ResourceManager.GetString("AddNoteGoalNameSubheading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note saved.
        /// </summary>
        public static string AddNoteHeading {
            get {
                return ResourceManager.GetString("AddNoteHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum of 10 notes can be added..
        /// </summary>
        public static string AddNoteMaximumNoteError {
            get {
                return ResourceManager.GetString("AddNoteMaximumNoteError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please add personal goals to start adding note..
        /// </summary>
        public static string AddNoteNoPersonalGoalAvailable {
            get {
                return ResourceManager.GetString("AddNoteNoPersonalGoalAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This command cannot be used on conversation messages sent by a bot..
        /// </summary>
        public static string AddNoteNotAllowedForBotMessage {
            get {
                return ResourceManager.GetString("AddNoteNotAllowedForBotMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note:.
        /// </summary>
        public static string AddNoteNoteSubheading {
            get {
                return ResourceManager.GetString("AddNoteNoteSubheading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type a note or paste one from a colleague or customer about your progress..
        /// </summary>
        public static string AddNotePlaceHolder {
            get {
                return ResourceManager.GetString("AddNotePlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * **To add note in a goal :** Go to your personal goals tab..
        /// </summary>
        public static string AddNotesBulletPoint {
            get {
                return ResourceManager.GetString("AddNotesBulletPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source:.
        /// </summary>
        public static string AddNoteSourceSubheading {
            get {
                return ResourceManager.GetString("AddNoteSourceSubheading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a note.
        /// </summary>
        public static string AddNoteTaskModuleTitle {
            get {
                return ResourceManager.GetString("AddNoteTaskModuleTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a note against a goal about your progress..
        /// </summary>
        public static string AddNoteTitleText {
            get {
                return ResourceManager.GetString("AddNoteTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your personal goal start date and end date should be within team goal start date and end date to align your goals..
        /// </summary>
        public static string AlignGoalDateConflict {
            get {
                return ResourceManager.GetString("AlignGoalDateConflict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while deleting personal goal details from storage..
        /// </summary>
        public static string AlignGoalErrorDeletingData {
            get {
                return ResourceManager.GetString("AlignGoalErrorDeletingData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}, you have not added any personal goals. Please add some to align your personal goals with team goals..
        /// </summary>
        public static string AlignGoalNoPersonalGoalsAdded {
            get {
                return ResourceManager.GetString("AlignGoalNoPersonalGoalsAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}, No teams goals are available to align your goals..
        /// </summary>
        public static string AlignGoalNoTeamGoalsAdded {
            get {
                return ResourceManager.GetString("AlignGoalNoTeamGoalsAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * Align personal goal with team&apos;s goal..
        /// </summary>
        public static string AlignGoalsBulletPoint {
            get {
                return ResourceManager.GetString("AlignGoalsBulletPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Align goals.
        /// </summary>
        public static string AlignGoalsButtonText {
            get {
                return ResourceManager.GetString("AlignGoalsButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Align goal.
        /// </summary>
        public static string AlignGoalTaskModuleTitle {
            get {
                return ResourceManager.GetString("AlignGoalTaskModuleTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chat 1:1 with Goal Tracker app and navigate to the &quot;Goals&quot; tab to add personal goals, align with team goals, and add notes..
        /// </summary>
        public static string AlignTeamGoalsBulletPoint {
            get {
                return ResourceManager.GetString("AlignTeamGoalsBulletPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome icon.
        /// </summary>
        public static string AltTextForWelcomeCardImage {
            get {
                return ResourceManager.GetString("AltTextForWelcomeCardImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Bi-weekly reminder].
        /// </summary>
        public static string Bi_weeklyReminderTypeString {
            get {
                return ResourceManager.GetString("Bi-weeklyReminderTypeString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bot failure.
        /// </summary>
        public static string BotFailureTitle {
            get {
                return ResourceManager.GetString("BotFailureTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string ChangeAlignmentNoActionText {
            get {
                return ResourceManager.GetString("ChangeAlignmentNoActionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string ChangeAlignmentYesActionText {
            get {
                return ResourceManager.GetString("ChangeAlignmentYesActionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All goals aligned in other team will be removed. Do you want to continue?.
        /// </summary>
        public static string ConfirmChangeAlignment {
            get {
                return ResourceManager.GetString("ConfirmChangeAlignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Let&apos;s get started!.
        /// </summary>
        public static string ContentText {
            get {
                return ResourceManager.GetString("ContentText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string EditButtonText {
            get {
                return ResourceManager.GetString("EditButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit goals.
        /// </summary>
        public static string EditGoalsActionText {
            get {
                return ResourceManager.GetString("EditGoalsActionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click on Edit goals to edit any previously set team goals..
        /// </summary>
        public static string EditGoalsCardTitleTextTeam {
            get {
                return ResourceManager.GetString("EditGoalsCardTitleTextTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click on Edit goals to edit any previously set team goals..
        /// </summary>
        public static string EditGoalsCommandCardText {
            get {
                return ResourceManager.GetString("EditGoalsCommandCardText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit note.
        /// </summary>
        public static string EditNoteTaskModuleTitle {
            get {
                return ResourceManager.GetString("EditNoteTaskModuleTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit personal goals.
        /// </summary>
        public static string EditPersonalGoal {
            get {
                return ResourceManager.GetString("EditPersonalGoal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit your goals.
        /// </summary>
        public static string EditPersonalGoalTaskModuleTitle {
            get {
                return ResourceManager.GetString("EditPersonalGoalTaskModuleTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit goals.
        /// </summary>
        public static string EditTeamGoalsActionText {
            get {
                return ResourceManager.GetString("EditTeamGoalsActionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit team goals.
        /// </summary>
        public static string EditTeamGoalTaskModuleTitle {
            get {
                return ResourceManager.GetString("EditTeamGoalTaskModuleTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong and I can’t do that right now. Try again in a few minutes..
        /// </summary>
        public static string ErrorSavingPersonalGoalData {
            get {
                return ResourceManager.GetString("ErrorSavingPersonalGoalData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong and I can’t do that right now. Try again in a few minutes..
        /// </summary>
        public static string ErrorSavingTeamGoalData {
            get {
                return ResourceManager.GetString("ErrorSavingTeamGoalData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error in updating personal goal detail data..
        /// </summary>
        public static string ErrorUpdatingPersonalGoalData {
            get {
                return ResourceManager.GetString("ErrorUpdatingPersonalGoalData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error in Updating team goal detail data..
        /// </summary>
        public static string ErrorUpdatingTeamGoalData {
            get {
                return ResourceManager.GetString("ErrorUpdatingTeamGoalData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong and I can’t do that right now. Try again in a few minutes..
        /// </summary>
        public static string GenericErrorMessage {
            get {
                return ResourceManager.GetString("GenericErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goal.
        /// </summary>
        public static string GoalBucketText {
            get {
                return ResourceManager.GetString("GoalBucketText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes can be added only during an active goal cycle..
        /// </summary>
        public static string GoalCycleEndedErrorForAddingNote {
            get {
                return ResourceManager.GetString("GoalCycleEndedErrorForAddingNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This note has been deleted. Please add new note..
        /// </summary>
        public static string GoalCycleEndedMessage {
            get {
                return ResourceManager.GetString("GoalCycleEndedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only one goal cycle can be active at a time..
        /// </summary>
        public static string GoalCycleRunningText {
            get {
                return ResourceManager.GetString("GoalCycleRunningText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The goal has been deleted..
        /// </summary>
        public static string GoalIsDeletedErrorText {
            get {
                return ResourceManager.GetString("GoalIsDeletedErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A gentle reminder to update the status of your goals and add  notes on your progress..
        /// </summary>
        public static string GoalReminderCardContentText {
            get {
                return ResourceManager.GetString("GoalReminderCardContentText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A gentle reminder.
        /// </summary>
        public static string GoalReminderCardTitle {
            get {
                return ResourceManager.GetString("GoalReminderCardTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} aligned.
        /// </summary>
        public static string GoalStatusAlignedText {
            get {
                return ResourceManager.GetString("GoalStatusAlignedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Progress summary.
        /// </summary>
        public static string GoalStatusCardTitle {
            get {
                return ResourceManager.GetString("GoalStatusCardTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to collapse.
        /// </summary>
        public static string GoalStatusChevronDownImageAltText {
            get {
                return ResourceManager.GetString("GoalStatusChevronDownImageAltText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to expand.
        /// </summary>
        public static string GoalStatusChevronUpImageAltText {
            get {
                return ResourceManager.GetString("GoalStatusChevronUpImageAltText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed.
        /// </summary>
        public static string GoalStatusCompletedHeader {
            get {
                return ResourceManager.GetString("GoalStatusCompletedHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 99/99.
        /// </summary>
        public static string GoalStatusDefaultTeamGoalEndDate {
            get {
                return ResourceManager.GetString("GoalStatusDefaultTeamGoalEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 00/00.
        /// </summary>
        public static string GoalStatusDefaultTeamGoalStartDate {
            get {
                return ResourceManager.GetString("GoalStatusDefaultTeamGoalStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Deleted].
        /// </summary>
        public static string GoalStatusDeletedText {
            get {
                return ResourceManager.GetString("GoalStatusDeletedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goal cycle.
        /// </summary>
        public static string GoalStatusGoalCycleText {
            get {
                return ResourceManager.GetString("GoalStatusGoalCycleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In progress.
        /// </summary>
        public static string GoalStatusInProgressHeader {
            get {
                return ResourceManager.GetString("GoalStatusInProgressHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The team goals have not been aligned by any team member..
        /// </summary>
        public static string GoalStatusNoGoalsAligned {
            get {
                return ResourceManager.GetString("GoalStatusNoGoalsAligned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No team goals are available yet..
        /// </summary>
        public static string GoalStatusNoTeamGoalAvailable {
            get {
                return ResourceManager.GetString("GoalStatusNoTeamGoalAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not started.
        /// </summary>
        public static string GoalStatusNotStartedHeader {
            get {
                return ResourceManager.GetString("GoalStatusNotStartedHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        public static string GoalStatusTotalHeader {
            get {
                return ResourceManager.GetString("GoalStatusTotalHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * Add note.
        /// </summary>
        public static string HelpCardAddNotesBulletPoint {
            get {
                return ResourceManager.GetString("HelpCardAddNotesBulletPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of supported commands are:.
        /// </summary>
        public static string HelpCardContent {
            get {
                return ResourceManager.GetString("HelpCardContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * Goal status.
        /// </summary>
        public static string HelpCardGoalStatusBulletPoint {
            get {
                return ResourceManager.GetString("HelpCardGoalStatusBulletPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * Set goals.
        /// </summary>
        public static string HelpCardSetGoalsBulletPoint {
            get {
                return ResourceManager.GetString("HelpCardSetGoalsBulletPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * Set team goals.
        /// </summary>
        public static string HelpCardSetTeamGoalsBulletPoint {
            get {
                return ResourceManager.GetString("HelpCardSetTeamGoalsBulletPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I am currently installed in Teams scope to reply to text messages. Please message me with supported command..
        /// </summary>
        public static string InformationAboutBotMessageLimitation {
            get {
                return ResourceManager.GetString("InformationAboutBotMessageLimitation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid tenant detected..
        /// </summary>
        public static string InvalidTenantText {
            get {
                return ResourceManager.GetString("InvalidTenantText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Monthly reminder].
        /// </summary>
        public static string MonthlyReminderTypeString {
            get {
                return ResourceManager.GetString("MonthlyReminderTypeString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editing of goals is possible only during an active goal cycle..
        /// </summary>
        public static string NoActiveGoalOrGoalCycleEndedError {
            get {
                return ResourceManager.GetString("NoActiveGoalOrGoalCycleEndedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aligning goals is possible only during an active goal cycle..
        /// </summary>
        public static string NoActiveGoalOrGoalCycleEndedErrorForAlignGoal {
            get {
                return ResourceManager.GetString("NoActiveGoalOrGoalCycleEndedErrorForAlignGoal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Either goals you are looking for have been deleted or this goal cycle is inactive. Please align your goal with active team goals..
        /// </summary>
        public static string NoActiveGoalOrGoalCycleEndedErrorForAligningGoal {
            get {
                return ResourceManager.GetString("NoActiveGoalOrGoalCycleEndedErrorForAligningGoal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This note has been deleted. Please try to add new note..
        /// </summary>
        public static string NoteIsDeletedErrorText {
            get {
                return ResourceManager.GetString("NoteIsDeletedErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note.
        /// </summary>
        public static string NoteText {
            get {
                return ResourceManager.GetString("NoteText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add note.
        /// </summary>
        public static string PersonalGoalAddNoteButtonText {
            get {
                return ResourceManager.GetString("PersonalGoalAddNoteButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goal cycle:  {0} - {1}..
        /// </summary>
        public static string PersonalGoalCardCycleText {
            get {
                return ResourceManager.GetString("PersonalGoalCardCycleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string PersonalGoalEditButtonText {
            get {
                return ResourceManager.GetString("PersonalGoalEditButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Your goal cycle will be ended in next 3 days].
        /// </summary>
        public static string PersonalGoalEndingAfterThreeDays {
            get {
                return ResourceManager.GetString("PersonalGoalEndingAfterThreeDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;Your goals&lt;/b&gt;.
        /// </summary>
        public static string PersonalGoalListCardTitle {
            get {
                return ResourceManager.GetString("PersonalGoalListCardTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not started.
        /// </summary>
        public static string PersonalGoalStatusNotStarted {
            get {
                return ResourceManager.GetString("PersonalGoalStatusNotStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Quarterly reminder].
        /// </summary>
        public static string QuarterlyReminderTypeString {
            get {
                return ResourceManager.GetString("QuarterlyReminderTypeString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to **Add note** - Lets you write a note or paste one from colleague or customer about your progress.
        /// </summary>
        public static string SaveNotesBulletPoint {
            get {
                return ResourceManager.GetString("SaveNotesBulletPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set goals.
        /// </summary>
        public static string SetGoalsActionText {
            get {
                return ResourceManager.GetString("SetGoalsActionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to **Set goals** - Lets you add or edit personal goals.
        /// </summary>
        public static string SetGoalsBulletPoint {
            get {
                return ResourceManager.GetString("SetGoalsBulletPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set goal.
        /// </summary>
        public static string SetGoalsButtonText {
            get {
                return ResourceManager.GetString("SetGoalsButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Now, its time to set your team&apos;s goal! I am here to help you and your team to set team&apos;s goal..
        /// </summary>
        public static string SetGoalsCardTitleTextTeam {
            get {
                return ResourceManager.GetString("SetGoalsCardTitleTextTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click on Set goals to add or edit personal goals.
        /// </summary>
        public static string SetGoalsCommandCardText {
            get {
                return ResourceManager.GetString("SetGoalsCommandCardText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set goal.
        /// </summary>
        public static string SetGoalTaskModuleTitle {
            get {
                return ResourceManager.GetString("SetGoalTaskModuleTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set personal goals.
        /// </summary>
        public static string SetPersonalGoalTaskModuleTitle {
            get {
                return ResourceManager.GetString("SetPersonalGoalTaskModuleTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set goal.
        /// </summary>
        public static string SetTeamGoalsActionText {
            get {
                return ResourceManager.GetString("SetTeamGoalsActionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * **For team owners:**.
        /// </summary>
        public static string SetTeamGoalsBulletPoint {
            get {
                return ResourceManager.GetString("SetTeamGoalsBulletPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set goals.
        /// </summary>
        public static string SetTeamGoalsButtonText {
            get {
                return ResourceManager.GetString("SetTeamGoalsButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set your teams&apos;s goal.
        /// </summary>
        public static string SetTeamGoalsCardText {
            get {
                return ResourceManager.GetString("SetTeamGoalsCardText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goals will be shared with your team members to help them align with their own goals..
        /// </summary>
        public static string SetTeamGoalsCardTextBody {
            get {
                return ResourceManager.GetString("SetTeamGoalsCardTextBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set team goals.
        /// </summary>
        public static string SetTeamGoalTaskModuleTitle {
            get {
                return ResourceManager.GetString("SetTeamGoalTaskModuleTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * Show progress of goals..
        /// </summary>
        public static string ShowProgressBulletPoint {
            get {
                return ResourceManager.GetString("ShowProgressBulletPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hint: outlook or praise( you can also use message action to pick up sender’s name).
        /// </summary>
        public static string SourceNamePlaceHolder {
            get {
                return ResourceManager.GetString("SourceNamePlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source.
        /// </summary>
        public static string SourceText {
            get {
                return ResourceManager.GetString("SourceText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string SubmitActionText {
            get {
                return ResourceManager.GetString("SubmitActionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid command for task module fetch activity. Command is: {0}.
        /// </summary>
        public static string TaskModuleInvalidCommandText {
            get {
                return ResourceManager.GetString("TaskModuleInvalidCommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goal cycle:  {0} - {1}..
        /// </summary>
        public static string TeamGoalCardCycleTextForTeam {
            get {
                return ResourceManager.GetString("TeamGoalCardCycleTextForTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goal cycle: {1} - {2}. Set by {0}.
        /// </summary>
        public static string TeamGoalCardCycleTextForTeamMembers {
            get {
                return ResourceManager.GetString("TeamGoalCardCycleTextForTeamMembers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Team goal cycle will be ended in next 3 days].
        /// </summary>
        public static string TeamGoalEndingAfterThreeDays {
            get {
                return ResourceManager.GetString("TeamGoalEndingAfterThreeDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;Your goals&lt;/b&gt;.
        /// </summary>
        public static string TeamGoalListCardTitleForTeam {
            get {
                return ResourceManager.GetString("TeamGoalListCardTitleForTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;Team goals&lt;/b&gt;.
        /// </summary>
        public static string TeamGoalListCardTitleForTeamMembers {
            get {
                return ResourceManager.GetString("TeamGoalListCardTitleForTeamMembers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * Type &quot;@Goal Tracker team goals&quot; in a post in this channel to set team goals, or click the button below to get started..
        /// </summary>
        public static string TeamGoalsBulletPoint {
            get {
                return ResourceManager.GetString("TeamGoalsBulletPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I&apos;m Goal Tracker, and I&apos;m here to help this team set and track personal and team goals. .
        /// </summary>
        public static string TeamsWelcomeCardContent {
            get {
                return ResourceManager.GetString("TeamsWelcomeCardContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What team members can do:.
        /// </summary>
        public static string TeamsWelcomeSubHeaderText {
            get {
                return ResourceManager.GetString("TeamsWelcomeSubHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View goals.
        /// </summary>
        public static string ViewGoalsButtonText {
            get {
                return ResourceManager.GetString("ViewGoalsButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Weekly reminder].
        /// </summary>
        public static string WeeklyReminderTypeString {
            get {
                return ResourceManager.GetString("WeeklyReminderTypeString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I&apos;m Goal Tracker, and I&apos;m here to help you set and track goals..
        /// </summary>
        public static string WelcomeCardContent {
            get {
                return ResourceManager.GetString("WelcomeCardContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome!.
        /// </summary>
        public static string WelcomeCardTitle {
            get {
                return ResourceManager.GetString("WelcomeCardTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here are the commands I follow and what they do:.
        /// </summary>
        public static string WelcomeSubHeaderText {
            get {
                return ResourceManager.GetString("WelcomeSubHeaderText", resourceCulture);
            }
        }
    }
}
